services:
  db:
    image: mysql:9.1
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_container
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    depends_on:
      - db
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    tty: true
    restart: always
    stdin_open: true

volumes:
  db-data:
